### ISSUE TITLE
gevent requires libevent

### ISSUE THREAD

**Issue by pearkes** [zachwill/flask_heroku#1]
I ran through setup and stumbled across some errors on install of gevent.

Turns out you need libevent to run gevent. 

```
apt-get install libevent-dev
```

This is also  simple with [homebrew](http://mxcl.github.com/homebrew/) on os x.

```
brew install libevent
```

Cheers!

Jack

**Comment by zachwill** [comment]
Nice — thanks for the heads up.

I've updated the README to include both methods of installing libevent.
