### ISSUE TITLE
Heroku push rejected, no Cedar-supported app detected

### ISSUE THREAD

**Issue by shaicohen** [zachwill/flask_heroku#4]
Shai.Cohen@SHAICOHEN-PC ~/.ssh/blooming-wind-6746 (master)
$ git push heroku master
Enter passphrase for key '/c/Users/Shai.Cohen/.ssh/id_rsa':
Counting objects: 15, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (15/15), 2.79 KiB, done.
Total 15 (delta 0), reused 0 (delta 0)

-----> Heroku receiving push
 !     Heroku push rejected, no Cedar-supported app detected

To git@heroku.com:growing-planet-4986.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:growing-planet-4986.git'

**Comment by zachwill** [comment]
Hey **shaicohen**,

Can I see your app? If you create a repo on your Github account, it'd be easier to diagnose the problem.

Thanks.

Zach

**Comment by shaicohen** [comment]
Sure! 

I just created a repo on my account..

10x!
Shai

**Comment by zachwill** [comment]
Is [TestJava](https://github.com/shaicohen/TestJava) the repo?

**Comment by shaicohen** [comment]
Yep..

**Comment by zachwill** [comment]
Hmmm, don't think I can help you. Seems like you're using a Java application, and this repository is for Python and Flask applications on Heroku.

**Comment by shaicohen** [comment]
BTW -- I followed the instructions from https://github.com/heroku/java-workbook.

**Comment by zachwill** [comment]
I could help you if it was a Python application. You might consider messaging @fabiokung (here's his [Twitter account](https://twitter.com/#!/fabiokung)). Judging by his repos and [blog post](http://fabiokung.com/2011/08/06/running-java-web-applications-on-heroku-cedar-stack/), he seems to know about using Java on Heroku.

**Comment by shaicohen** [comment]
OOhhh OK.. 
I probably missed one step, I try it again and it is working now.. 

10x again!
Shai

**Comment by jamesward** [comment]
Can you collab me into the project or open a Heroku support request?  To add me do:

```
heroku sharing:add jw@heroku.com
```

**Comment by jamesward** [comment]
Oh, actually I take that back.  Adding me probably won't help because I probably won't be able to see the code since the push failed.  Make sure you have the proper build file in your git repo (committed).  If it's a Maven project then you should have a pom.xml file in the project root.  Feel free to email me if you need any help.
