### ISSUE TITLE
Use Gunicorn instead

### ISSUE THREAD

**Issue by kennethreitz** [zachwill/flask_heroku#5]
Gunicorn would make the whole `bootstrap.py` thing unnecessary. It also spins a configured number of workers, and has an incredibly excellent gevent worker type (as well as tornado, if you're into that :). 

Just a suggestion :)

**Comment by zachwill** [comment]
Nice, sounds like a good suggestion. Do you suggest 3 Gunicorn workers like the [Dev Center article](http://devcenter.heroku.com/articles/python#using_a_different_wsgi_server)?

**Comment by kennethreitz** [comment]
It depends on the application. The only real limitation is RAM. For small memory applications, I use 9+ gevent workers. If it's a django app (which takes quite a bit more memory), 3 or 4 is best.

**Comment by kennethreitz** [comment]
So, 3 is a good default.

**Comment by zachwill** [comment]
Just created a branch and I'm pretty impressed. Did not expect it to be this easy to use.

Will update the documentation and make Gunicorn default — good call, @kennethreitz.

**Comment by kennethreitz** [comment]
Awesome ;)

@benoitc is the man to thank ;)

**Comment by kennethreitz** [comment]
:sparkles: :cake: :sparkles:

**Comment by kennethreitz** [comment]
Just took a look at the branch. Awesome ;)

If you still want to use gevent (highly recommended) add  `-k gevent` to the command.

**Comment by zachwill** [comment]
Does `gevent` still need to be in the `requirements.txt`? Or is it already installed with `gunicorn`?

**Comment by kennethreitz** [comment]
No, it's an optional dependency, so it needs to be `requirements.txt`.

**Comment by zachwill** [comment]
Ship it.

:shipit:
