### ISSUE TITLE
Heroku git push rejected, No cedar supported app

### ISSUE THREAD

**Issue by kshitizrimal** [zachwill/flask_heroku#9]
I tweak the basic flaskr app  available in git to test to launch in heroku, i am just beginning to ue heroku so i wanted to test some example app by deploying it  This is the error i get

C:\Users\monk\Desktop\flask-master\examples\flaskr>git push heroku master
Counting objects: 935, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (880/880), done.
Writing objects: 100% (935/935), 2.63 MiB | 6 KiB/s, done.
Total 935 (delta 107), reused 0 (delta 0)
 !     Heroku push rejected, no Cedar-supported app detected

To git@heroku.com:stark-badlands-6689.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:stark-badlands-6689.git'

I try to follow some of the issues in this guthub as well but no luck for me. i tried pushing it via venv as well but same problem i have done the steps in this issue

https://github.com/zachwill/flask_heroku/issues/3

but it doesn work for me

the commands 

git init && git aa
git ci -am "First commit"

doesn't work in my command prompt as it says 

git: 'aa' is not a git command. See 'git --help'.

and 

git: 'ci' is not a git command. See 'git --help'.

Did you mean this?
        gui

I am getting to frustrated with this heroku and flask already please help.

the olny thing i have changed in original flaskr example is this

import os (at beginning)

port = int(os.environ.get('PORT', 5000))
app.run(host='0.0.0.0', port=port)
at the end of the line

 i have also added a proc file 
web: python flaskr.py

**Comment by kshitizrimal** [comment]
here is the code

https://github.com/kshitizrimal/flaskr-modified

**Comment by zachwill** [comment]
I believe you won't be able to use SQLite on Heroku, just a heads up. I think your issue might be with `requirement.txt` should be named `requirements.txt`. Hope that helps.

Closing and looping in @kennethreitz if your issues persist — since you're using a different codebase than this repo.

**Comment by kennethreitz** [comment]
Correct.

**Comment by kshitizrimal** [comment]
i think the problem as you said is with requirement file.. i have managed to work it with sqlite as well. it works on heroku :) thank you for your time
